name: E2E Tests (Axios Client)

on:
  push:
    branches: [ tester ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: 
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run build

      # รัน server แบบ background และเก็บ PID
      - name: Start Express Server
        run: |
          RUN_E2E=true npx ts-node src/index.ts &
          echo $! > server.pid
        env:
          PORT: 3000

      # รอ server พร้อมด้วย health check
      - name: Wait for server to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:3000/health >/dev/null; then
              echo "Server is ready!"
              break
            fi
            echo "Waiting for server..."
            sleep 1
          done

      - name: Run E2E Tests
        run: npm run test:e2e

      # ปิด server หลังจบ workflow
      - name: Stop server
        if: always()
        run: |
          kill $(cat server.pid) || true

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-logs
          path: |
            ./test-results
            ./coverage
            ./logs
