name: E2E Tests (Axios Client)

on:
  push:
    branches: [ tester ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: '20' # แนะนำให้อัพเดทเป็น Node 20 หากโค้ดรองรับ
      
      - name: Install dependencies
        run: npm ci
        
      # 1. Build TypeScript 
      - name: Compile TypeScript
        run: npm run build
        
      # 2. Start Express Server ใน Background (รัน node dist/index.js)
      - name: Start Express Server
        run: npm start & 
        env:
          # หากต้องการใช้ Test DB URI ควรตั้งค่าใน Secrets แล้วเรียกใช้ที่นี่
          PORT: 3000
        
      # Wait 10 วินาทีให้ Server และ DB Connection (Mongoose) พร้อม
      - name: Wait for server to be ready
        run: sleep 10s 

      # 3. รัน E2E Tests (ใช้ Axios/HTTP Client)
      - name: Run E2E Tests
        run: npm run test:e2e
        # ไม่จำเป็นต้องตั้ง NODE_ENV=test เนื่องจาก server รันแบบ full stack 
      
      # 4. อัปโหลด logs/artifacts
      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-logs
          path: ./test-results || ./coverage || ./logs
